application: twonikeshop
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /stylesheet
  static_dir: stylesheet
- url: /js
  static_dir: js
- url: /images
  static_dir: images

- url: /.*
  script: helloworld.application
